[mongodb]
mongodb-dev.rawsd.in

[catalogue]
catalogue-dev.rawsd.in 

[redis]
redis-dev.rawsd.in 

[user]
user-dev.rawsd.in 

[cart]
cart-dev.rawsd.in 

[mysql]
mysql-dev.rawsd.in

[shipping]
shipping-dev.rawsd.in 

[payment]
payment-dev.rawsd.in 

[rabbitmq]
rabbitmq-dev.rawsd.in 

[frontend]
frontend-dev.rawsd.in

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rawsd.in 
REDIS_HOST=redis-dev.rawsd.in
CATALOGUE_HOST=catalogue-dev.rawsd.in
USER_HOST=user-dev.rawsd.in
CART_HOST=cart-dev.rawsd.in
MYSQL_HOST=mysql-dev.rawsd.in
SHIPPING_HOST=shipping-dev.rawsd.in
RABBITMQ_HOST=rabbitmq-dev.rawsd.in
PAYMENT_HOST=payment-dev.rawsd.in
